data = [
    {"name": "Cristiano Ronaldo", "follower_count": 660, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 505, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 419, "description": "Musician and actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 393, "description": "Media personality", "country": "United States"},
    {"name": "Dwayne Johnson", "follower_count": 393, "description": "Actor and wrestler", "country": "United States"},
    {"name": "Ariana Grande", "follower_count": 375, "description": "Musician and actress", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 356, "description": "Media personality", "country": "United States"},
    {"name": "Beyoncé", "follower_count": 311, "description": "Musician and actress", "country": "United States"},
    {"name": "Khloé Kardashian", "follower_count": 302, "description": "Media personality", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 294, "description": "Musician", "country": "Canada"},
    {"name": "Kendall Jenner", "follower_count": 293, "description": "Model and media personality", "country": "United States"},
    {"name": "Taylor Swift", "follower_count": 290, "description": "Musician", "country": "United States"},
    {"name": "Virat Kohli", "follower_count": 270, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "follower_count": 261, "description": "Singer and actress", "country": "United States"},
    {"name": "Nicki Minaj", "follower_count": 259, "description": "Musician", "country": "United States"},
    {"name": "Neymar Jr.", "follower_count": 254, "description": "Footballer", "country": "Brazil"},
    {"name": "Miley Cyrus", "follower_count": 240, "description": "Musician and actress", "country": "United States"},
    {"name": "Kourtney Kardashian", "follower_count": 229, "description": "Media personality", "country": "United States"},
    {"name": "Kevin Hart", "follower_count": 220, "description": "Comedian and actor", "country": "United States"},
    {"name": "Zendaya", "follower_count": 215, "description": "Actress and singer", "country": "United States"},
    {"name": "Drake", "follower_count": 211, "description": "Musician", "country": "Canada"},
    {"name": "Billie Eilish", "follower_count": 210, "description": "Musician", "country": "United States"},
    {"name": "Bad Bunny", "follower_count": 202, "description": "Musician", "country": "Puerto Rico"},
    {"name": "David Beckham", "follower_count": 185, "description": "Footballer", "country": "United Kingdom"},
    {"name": "Rihanna", "follower_count": 181, "description": "Musician and entrepreneur", "country": "Barbados"},
    {"name": "Cardi B", "follower_count": 178, "description": "Musician", "country": "United States"},
    {"name": "Shakira", "follower_count": 175, "description": "Musician", "country": "Colombia"},
    {"name": "LeBron James", "follower_count": 172, "description": "Basketball player", "country": "United States"},
    {"name": "Katy Perry", "follower_count": 204, "description": "Musician", "country": "United States"},
    {"name": "Ellen DeGeneres", "follower_count": 136, "description": "Comedian and TV host", "country": "United States"},
    {"name": "Kylian Mbappé", "follower_count": 124, "description": "Footballer", "country": "France"},
    {"name": "Gal Gadot", "follower_count": 108, "description": "Actress", "country": "Israel"},
    {"name": "Lisa (BLACKPINK)", "follower_count": 106, "description": "Musician", "country": "Thailand"},
    {"name": "Vin Diesel", "follower_count": 103, "description": "Actor", "country": "United States"},
    {"name": "Narendra Modi", "follower_count": 96, "description": "Prime Minister of India", "country": "India"},
    {"name": "Shraddha Kapoor", "follower_count": 94, "description": "Actress", "country": "India"},
    {"name": "Priyanka Chopra", "follower_count": 92, "description": "Actress", "country": "India"},
    {"name": "Dua Lipa", "follower_count": 88, "description": "Musician", "country": "United Kingdom"},
    {"name": "Jennie (BLACKPINK)", "follower_count": 87, "description": "Musician", "country": "South Korea"},
    {"name": "Alia Bhatt", "follower_count": 86, "description": "Actress", "country": "India"},
    {"name": "Rosé (BLACKPINK)", "follower_count": 84, "description": "Musician", "country": "New Zealand"},
    {"name": "Khaby Lame", "follower_count": 80, "description": "Content creator", "country": "Italy"},
    {"name": "Katrina Kaif", "follower_count": 80, "description": "Actress", "country": "India"},
    {"name": "Deepika Padukone", "follower_count": 80, "description": "Actress", "country": "India"},
    {"name": "Jisoo (BLACKPINK)", "follower_count": 79, "description": "Musician", "country": "South Korea"},
    {"name": "The Weeknd", "follower_count": 75, "description": "Musician", "country": "Canada"},
    {"name": "Emma Watson", "follower_count": 73, "description": "Actress and activist", "country": "United Kingdom"},
    {"name": "MrBeast", "follower_count": 72, "description": "YouTuber and philanthropist", "country": "United States"},
    {"name": "Zlatan Ibrahimović", "follower_count": 71, "description": "Footballer", "country": "Sweden"},
    {"name": "Shawn Mendes", "follower_count": 70, "description": "Musician", "country": "Canada"},
    {"name": "Gigi Hadid", "follower_count": 69, "description": "Model", "country": "United States"},
    {"name": "Zayn Malik", "follower_count": 66, "description": "Musician", "country": "United Kingdom"},
    {"name": "Millie Bobby Brown", "follower_count": 65, "description": "Actress", "country": "United Kingdom"},
    {"name": "Huda Kattan", "follower_count": 63, "description": "Makeup artist and entrepreneur", "country": "United States"},
    {"name": "Bruno Mars", "follower_count": 61, "description": "Musician", "country": "United States"},
    {"name": "Trevor Noah", "follower_count": 60, "description": "Comedian and host", "country": "South Africa"},
    {"name": "Luis Suárez", "follower_count": 59, "description": "Footballer", "country": "Uruguay"},
    {"name": "Karol G", "follower_count": 70, "description": "Musician", "country": "Colombia"},
    {"name": "Salman Khan", "follower_count": 69, "description": "Actor", "country": "India"},
    {"name": "Will Smith", "follower_count": 69, "description": "Actor and producer", "country": "United States"},
    {"name": "Marcelo Vieira", "follower_count": 69, "description": "Footballer", "country": "Brazil"},
    {"name": "Anushka Sharma", "follower_count": 68, "description": "Actress", "country": "India"},
    {"name": "Kim Taehyung", "follower_count": 68, "description": "Musician", "country": "South Korea"},
    {"name": "Georgina Rodríguez", "follower_count": 67, "description": "Model", "country": "Spain"},
    {"name": "Akshay Kumar", "follower_count": 66, "description": "Actor", "country": "India"},
    {"name": "Sergio Ramos", "follower_count": 64, "description": "Footballer", "country": "Spain"},
    {"name": "Mohamed Salah", "follower_count": 64, "description": "Footballer", "country": "Egypt"},
    {"name": "Maluma", "follower_count": 64, "description": "Musician", "country": "Colombia"},
    {"name": "Camila Cabello", "follower_count": 64, "description": "Musician", "country": "United States"},
    {"name": "Anitta", "follower_count": 63, "description": "Musician", "country": "Brazil"},
    {"name": "Tom Holland", "follower_count": 63, "description": "Actor", "country": "United Kingdom"},
    {"name": "Paul Pogba", "follower_count": 63, "description": "Footballer", "country": "France"},
    {"name": "Lady Gaga", "follower_count": 61, "description": "Musician and actress", "country": "United States"},
    {"name": "Zac Efron", "follower_count": 60, "description": "Actor", "country": "United States"},
    {"name": "Leonardo DiCaprio", "follower_count": 60, "description": "Actor and environmentalist", "country": "United States"},
    {"name": "Travis Scott", "follower_count": 59, "description": "Musician", "country": "United States"},
    {"name": "Kriti Sanon", "follower_count": 58, "description": "Actress", "country": "India"},
    {"name": "Disha Patani", "follower_count": 61, "description": "Actress", "country": "India"},
    {"name": "Bella Hadid", "follower_count": 61, "description": "Model", "country": "United States"},
    {"name": "Adele", "follower_count": 58, "description": "Musician", "country": "United Kingdom"},
    {"name": "Chris Hemsworth", "follower_count": 58, "description": "Actor", "country": "Australia"},
    {"name": "Justin Timberlake", "follower_count": 57, "description": "Musician and actor", "country": "United States"},
    {"name": "Jacqueline Fernandez", "follower_count": 56, "description": "Actress", "country": "India"},
    {"name": "Urvashi Rautela", "follower_count": 55, "description": "Actress and model", "country": "India"},
    {"name": "Paris Hilton", "follower_count": 54, "description": "Media personality and entrepreneur", "country": "United States"},
    {"name": "Tyga", "follower_count": 53, "description": "Musician", "country": "United States"},
    {"name": "Jason Derulo", "follower_count": 52, "description": "Musician", "country": "United States"},
    {"name": "Joko Widodo", "follower_count": 58, "description": "President of Indonesia", "country": "Indonesia"},
    {"name": "Neha Kakkar", "follower_count": 58, "description": "Musician", "country": "India"},
    {"name": "Ronaldinho", "follower_count": 57, "description": "Footballer", "country": "Brazil"},
    {"name": "Karim Benzema", "follower_count": 56, "description": "Footballer", "country": "France"},
    {"name": "Raffi Ahmad", "follower_count": 56, "description": "Actor and TV host", "country": "Indonesia"},
    {"name": "Victoria Beckham", "follower_count": 55, "description": "Fashion designer and singer", "country": "United Kingdom"},
    {"name": "Snoop Dogg", "follower_count": 54, "description": "Musician", "country": "United States"},
    {"name": "BLACKPINK Official", "follower_count": 53, "description": "K-pop group", "country": "South Korea"},
    {"name": "Paris Saint-Germain", "follower_count": 52, "description": "Football club", "country": "France"},
    {"name": "Marvel Entertainment", "follower_count": 51, "description": "Media franchise", "country": "United States"},
    {"name": "Michelle Obama", "follower_count": 57, "description": "Author and former First Lady", "country": "United States"},
    {"name": "Stephen Curry", "follower_count": 58, "description": "Basketball player", "country": "United States"},
    {"name": "Nora Fatehi", "follower_count": 47, "description": "Actress and dancer", "country": "Canada"},
]

# def find_duplicates(data):
#     seen = set()
#     duplicates = []

#     for entry in data:
#         name = entry['name']
#         if name in seen:
#             duplicates.append(name)
#         else:
#             seen.add(name)
    
#     return duplicates

# # Run the check
# dupe_names = find_duplicates(data)
# print("Duplicate celebrities found:", dupe_names)
